//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuTaoHelper.Core.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Translations_ru_RU {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations_ru_RU() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HuTaoHelper.Core.Localization.Translations.ru-RU", typeof(Translations_ru_RU).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновлена информация об аккаунте &quot;$1&quot;.
        /// </summary>
        public static string LocAccountRefreshed {
            get {
                return ResourceManager.GetString("LocAccountRefreshed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый аккаунт:.
        /// </summary>
        public static string LocAddAccountHeader {
            get {
                return ResourceManager.GetString("LocAddAccountHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логин / почта.
        /// </summary>
        public static string LocAddAccountLoginHint {
            get {
                return ResourceManager.GetString("LocAddAccountLoginHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить цель уведомления.
        /// </summary>
        public static string LocAddNotificationTargetHeader {
            get {
                return ResourceManager.GetString("LocAddNotificationTargetHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация об аккаунтах обновлена.
        /// </summary>
        public static string LocAllAccountsRefreshed {
            get {
                return ResourceManager.GetString("LocAllAccountsRefreshed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка аутентификации аккаунта.
        /// </summary>
        public static string LocAuthenticationError {
            get {
                return ResourceManager.GetString("LocAuthenticationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аккаунт успешно аутентифицирован!.
        /// </summary>
        public static string LocAuthenticationSuccessful {
            get {
                return ResourceManager.GetString("LocAuthenticationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить имя:.
        /// </summary>
        public static string LocChangeTitleHeader {
            get {
                return ResourceManager.GetString("LocChangeTitleHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменённое имя (опционально).
        /// </summary>
        public static string LocChangeTitleHint {
            get {
                return ResourceManager.GetString("LocChangeTitleHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Награда ежедневного клика уже получена.
        /// </summary>
        public static string LocCheckInAlready {
            get {
                return ResourceManager.GetString("LocCheckInAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Награда получена: $1 $2шт..
        /// </summary>
        public static string LocCheckInReward {
            get {
                return ResourceManager.GetString("LocCheckInReward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПРИНЯТЬ.
        /// </summary>
        public static string LocDialogAccept {
            get {
                return ResourceManager.GetString("LocDialogAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ДОБАВИТЬ.
        /// </summary>
        public static string LocDialogAdd {
            get {
                return ResourceManager.GetString("LocDialogAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ОТМЕНА.
        /// </summary>
        public static string LocDialogCancel {
            get {
                return ResourceManager.GetString("LocDialogCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не найдена ни одна запущенная игра.
        /// </summary>
        public static string LocGameHandleNotFound {
            get {
                return ResourceManager.GetString("LocGameHandleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите запущенную игру:.
        /// </summary>
        public static string LocGameHandleSelectionHeader {
            get {
                return ResourceManager.GetString("LocGameHandleSelectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Язык изменён на Русский.
        /// </summary>
        public static string LocLanguageChanged {
            get {
                return ResourceManager.GetString("LocLanguageChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить аккаунт.
        /// </summary>
        public static string LocMenuAddAccount {
            get {
                return ResourceManager.GetString("LocMenuAddAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автоматизация.
        /// </summary>
        public static string LocMenuAutomation {
            get {
                return ResourceManager.GetString("LocMenuAutomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фоновая задача ежедневных отметок.
        /// </summary>
        public static string LocMenuAutomationDailyCheckIn {
            get {
                return ResourceManager.GetString("LocMenuAutomationDailyCheckIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить имя.
        /// </summary>
        public static string LocMenuChangeTitle {
            get {
                return ResourceManager.GetString("LocMenuChangeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выход.
        /// </summary>
        public static string LocMenuExit {
            get {
                return ResourceManager.GetString("LocMenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Язык.
        /// </summary>
        public static string LocMenuLanguage {
            get {
                return ResourceManager.GetString("LocMenuLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уведомления.
        /// </summary>
        public static string LocMenuNotificationTargets {
            get {
                return ResourceManager.GetString("LocMenuNotificationTargets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Повторить аутентификацию.
        /// </summary>
        public static string LocMenuReauthenticate {
            get {
                return ResourceManager.GetString("LocMenuReauthenticate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновить информацию.
        /// </summary>
        public static string LocMenuRefresh {
            get {
                return ResourceManager.GetString("LocMenuRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновить все аккаунты.
        /// </summary>
        public static string LocMenuRefreshAllAccounts {
            get {
                return ResourceManager.GetString("LocMenuRefreshAllAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string LocMenuRemove {
            get {
                return ResourceManager.GetString("LocMenuRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Инструменты.
        /// </summary>
        public static string LocMenuTools {
            get {
                return ResourceManager.GetString("LocMenuTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уведомление уже существует.
        /// </summary>
        public static string LocNotificationAlreadyExist {
            get {
                return ResourceManager.GetString("LocNotificationAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код уведомления.
        /// </summary>
        public static string LocNotificationCode {
            get {
                return ResourceManager.GetString("LocNotificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уведомление &quot;$1&quot; создано.
        /// </summary>
        public static string LocNotificationCreated {
            get {
                return ResourceManager.GetString("LocNotificationCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Токен бота.
        /// </summary>
        public static string LocNotificationTelegramBotToken {
            get {
                return ResourceManager.GetString("LocNotificationTelegramBotToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id чата.
        /// </summary>
        public static string LocNotificationTelegramChatId {
            get {
                return ResourceManager.GetString("LocNotificationTelegramChatId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле обязательно для заполнения.
        /// </summary>
        public static string LocRequiredField {
            get {
                return ResourceManager.GetString("LocRequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аутентификация.
        /// </summary>
        public static string LocWebLoginAuthentication {
            get {
                return ResourceManager.GetString("LocWebLoginAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to эту кнопку.
        /// </summary>
        public static string LocWebLoginButton {
            get {
                return ResourceManager.GetString("LocWebLoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, аутентифицируйтесь и нажмите.
        /// </summary>
        public static string LocWebLoginLabel {
            get {
                return ResourceManager.GetString("LocWebLoginLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Я не вижу данных аутентификации :(.
        /// </summary>
        public static string LocWebLoginNoAuthentication {
            get {
                return ResourceManager.GetString("LocWebLoginNoAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неправильный формат числа.
        /// </summary>
        public static string LocWrongIntFormat {
            get {
                return ResourceManager.GetString("LocWrongIntFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        public static string LogAddAccountPassword {
            get {
                return ResourceManager.GetString("LogAddAccountPassword", resourceCulture);
            }
        }
    }
}
